# Generated by Django 4.1 on 2022-09-01 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL("""
            INSERT INTO lettings_letting (
                id,
                name,
                category_id
            )
            SELECT
                id,
                name,
                category_id
            FROM
                oc_lettings_site_letting;
            
            INSERT INTO lettings_address (
                id,
                name,
                category_id
            )
            SELECT
                id,
                name,
                category_id
            FROM
                oc_lettings_site_address;

            """, reverse_sql="""
            INSERT INTO oc_lettings_site_letting (
                id,
                name,
                category_id
            )
            SELECT
                id,
                name,
                category_id
            FROM
                lettings_letting;
            
            INSERT INTO oc_lettings_site_address (
                id,
                name,
                category_id
            )
            SELECT
                id,
                name,
                category_id
            FROM
                lettings_address;
        """)
    ]
