version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  build-and-test:
    docker:
      - image: nardiotencha08/lettings
        auth:
          username: nardiotencha08
          password: nXt^9=Mi)8.U4wM
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: pytest

workflows:
  sample:
    jobs:
      - build-and-test
