version: 2.1

orbs:
  python: circleci/python@1.5.0
  docker: circleci/docker@2.1.3
  heroku: circleci/heroku@0.0.10

jobs:

  build-and-test:
    docker:
      - image: nardiotencha08/lettings:latest
        auth:
          username: ${dockerhub_username}
          password: ${dockerhub_password}
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: pytest    

  build-and-push:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check:
          docker-username: $dockerhub_username
          docker-password: $dockerhub_password
      - docker/build:
          image: nardiotencha08/lettings
      - docker/push:
          digest-path: /tmp/digest.txt
          image: nardiotencha08/lettings
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"


workflows:
  sample:
    jobs:
      - build-and-test
      - build-and-push
      - heroku/deploy-via-git